from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^home/aboutus/$', views.aboutus, name='aboutus'),
    url(r'^adminlogin/$', views.adminlogin, name='adminlogin'),
    url(r'^adminauth/$', views.adminauth, name='adminauth'),
    url(r'^admindash/$', views.admindash, name='admindash'),
    url(r'^emplist/$', views.emplist, name='emplist'),
    url(r'^empupdate/$', views.empupdate, name='empupdate'),
    url(r'^updateauth/$', views.updateauth, name='updateauth'),
    url(r'^bbstatus/$', views.bbstatus, name='bbstatus'),
    url(r'^withdraw/$', views.withdraw, name='withdraw'),
    url(r'^withdrawal/$', views.withdrawal, name='withdrawal'),
    url(r'^hist/$', views.hist, name='hist'),
    url(r'^histdisplay/$', views.histdisplay, name='histdisplay'),
    url(r'^equipstatus/$', views.equipstatus, name='equipstatus'),
    url(r'^emplogin/$', views.emplogin, name='emplogin'),
    url(r'^empnew/$', views.empnew, name='empnew'),
    url(r'^empnewsignup/$', views.empnewsignup, name='empnewsignup'),
    url(r'^empnewauth/$', views.empnewauth, name='empnewauth'),
    url(r'^empregister/$', views.empregister, name='empregister'),
    url(r'^emplogauth/$', views.emplogauth, name='emplogauth'),
    url(r'^emplogout/$', views.emplogout, name='emplogout'),
    url(r'^empdash/$', views.empdash, name='empdash'),
    url(r'^eprofile/$', views.eprofile, name='eprofile'),
    url(r'^empdonorlist/$', views.empdonorlist, name='empdonorlist'),
    url(r'^donatehome/$', views.donatehome, name='donatehome'),
    url(r'^donorlogin/$', views.donorlogin, name='donorlogin'),
    url(r'^donorsignup/$', views.donorsignup, name='donorsignup'),
    url(r'^donorregister/$', views.donorregister, name='donorregister'),
    url(r'^donorlogauth/$', views.donorlogauth, name='donorlogauth'),
    url(r'^donorlogout/$', views.donorlogout, name='donorlogout'),
    url(r'^donordash/$', views.donordash, name='donordash'),
    url(r'^dprofile/$', views.dprofile, name='dprofile'),
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^donation/$', views.donation, name='donation'),
]
